global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: ged
    metrics_path: /api/v1/actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080"]
  - job_name: postgres
    static_configs:
      - targets: ["postgres-exporter:9187"]

